In [1]:
import os
import pandas as pd

folder_path = r'C:\Users\Dell\Documents\download sql'

for file in os.listdir(folder_path):
    file_path = os.path.join(folder_path, file)
    
    # Check if it's a CSV file
    if os.path.isfile(file_path) and file.lower().endswith('.csv'):
        # Creates variable names matching downstream code:
        # e.g., 'olist_customers_dataset.csv' -> 'customers'
        # e.g., 'product_category_name_translation.csv' -> 'product_category_name_translation'
        var_name = (
            file.replace('olist_', '')
                .replace('_dataset', '')
                .split('.')[0]
                .lower()
        )
        try:
            df = pd.read_csv(file_path, engine='python', on_bad_lines='skip')
            globals()[var_name] = df
            print(f"✅ Created variable: {var_name}")
        except Exception as e:
            print(f"❌ Could not load {file}: {e}")

✅ Created variable: master_orders_clean
✅ Created variable: customers
✅ Created variable: geolocation
✅ Created variable: orders
✅ Created variable: order_items
✅ Created variable: order_payments
✅ Created variable: order_reviews
✅ Created variable: products
✅ Created variable: sellers
✅ Created variable: product_category_name_translation

In [2]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        print(f"{name}: {df.duplicated().sum()}")

df: 0
master_orders_clean: 0
customers: 0
geolocation: 261831
orders: 0
order_items: 0
order_payments: 0
order_reviews: 0
products: 0
sellers: 0
product_category_name_translation: 0

In [3]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        print(f"================ {name.upper()} ================")
        df.info()
        print("\n")

================ MASTER_ORDERS_CLEAN ================
<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  str
 14  seller_id                      118310 non-null  str
 15  shipping_limit_date            118310 non-null  str
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116600 non-null  str
 19  product_name_lenght            116600 non-null  float64
 20  product_description_lenght     116600 non-null  float64
 21  product_photos_qty             116600 non-null  float64
 22  product_weight_g               116600 non-null  float64
 23  product_length_cm              116600 non-null  float64
 24  product_height_cm              116600 non-null  float64
 25  product_width_cm               116600 non-null  float64
 26  product_category_name_english  116575 non-null  str
 27  seller_zip_code_prefix         118310 non-null  float64
 28  seller_city                    118310 non-null  str
 29  seller_state                   118310 non-null  str
 30  payment_sequential             119140 non-null  float64
 31  payment_type                   119140 non-null  str
 32  payment_installments           119140 non-null  float64
 33  payment_value                  119140 non-null  float64
 34  review_id                      118146 non-null  str
 35  review_score                   118146 non-null  float64
 36  review_comment_title           118144 non-null  str
 37  review_comment_message         118114 non-null  str
 38  review_creation_date           118146 non-null  str
 39  review_answer_timestamp        118146 non-null  str
dtypes: float64(15), int64(1), str(24)
memory usage: 36.4 MB


================ CUSTOMERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB


================ GEOLOCATION ================
<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB


================ ORDERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB


================ ORDER_ITEMS ================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB


================ ORDER_PAYMENTS ================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB


================ ORDER_REVIEWS ================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB


================ PRODUCTS ================
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB


================ SELLERS ================
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB


================ PRODUCT_CATEGORY_NAME_TRANSLATION ================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [4]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        initial_rows = len(df)
        df.drop_duplicates(inplace=True)
        dropped_count = initial_rows - len(df)
        print(f"Removed {dropped_count:,} duplicate rows from '{name}'. (New shape: {df.shape})")

Removed 0 duplicate rows from 'master_orders_clean'. (New shape: (119143, 40))
Removed 0 duplicate rows from 'customers'. (New shape: (99441, 5))
Removed 261,831 duplicate rows from 'geolocation'. (New shape: (738332, 5))
Removed 0 duplicate rows from 'orders'. (New shape: (99441, 8))
Removed 0 duplicate rows from 'order_items'. (New shape: (112650, 7))
Removed 0 duplicate rows from 'order_payments'. (New shape: (103886, 5))
Removed 0 duplicate rows from 'order_reviews'. (New shape: (99224, 7))
Removed 0 duplicate rows from 'products'. (New shape: (32951, 9))
Removed 0 duplicate rows from 'sellers'. (New shape: (3095, 4))
Removed 0 duplicate rows from 'product_category_name_translation'. (New shape: (71, 2))

In [5]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        # Select all text/object columns in the current DataFrame
        text_cols = df.select_dtypes(include=['object', 'string']).columns
        
        # Strip leading and trailing whitespace from text columns
        df[text_cols] = df[text_cols].apply(lambda x: x.str.strip())
        
        print(f"Cleaned whitespace in '{name}' | Shape: {df.shape}")

Cleaned whitespace in 'master_orders_clean' | Shape: (119143, 40)
Cleaned whitespace in 'customers' | Shape: (99441, 5)
Cleaned whitespace in 'geolocation' | Shape: (738332, 5)
Cleaned whitespace in 'orders' | Shape: (99441, 8)
Cleaned whitespace in 'order_items' | Shape: (112650, 7)
Cleaned whitespace in 'order_payments' | Shape: (103886, 5)
Cleaned whitespace in 'order_reviews' | Shape: (99224, 7)
Cleaned whitespace in 'products' | Shape: (32951, 9)
Cleaned whitespace in 'sellers' | Shape: (3095, 4)
Cleaned whitespace in 'product_category_name_translation' | Shape: (71, 2)

In [6]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        # Select all text/object columns in the current DataFrame
        text_cols = df.select_dtypes(include=['object', 'string']).columns
        
        # Apply title case to each text column
        df[text_cols] = df[text_cols].apply(lambda x: x.str.title())
        
        print(f"Standardized text (Title Case) in '{name}' | Shape: {df.shape}")

Standardized text (Title Case) in 'master_orders_clean' | Shape: (119143, 40)
Standardized text (Title Case) in 'customers' | Shape: (99441, 5)
Standardized text (Title Case) in 'geolocation' | Shape: (738332, 5)
Standardized text (Title Case) in 'orders' | Shape: (99441, 8)
Standardized text (Title Case) in 'order_items' | Shape: (112650, 7)
Standardized text (Title Case) in 'order_payments' | Shape: (103886, 5)
Standardized text (Title Case) in 'order_reviews' | Shape: (99224, 7)
Standardized text (Title Case) in 'products' | Shape: (32951, 9)
Standardized text (Title Case) in 'sellers' | Shape: (3095, 4)
Standardized text (Title Case) in 'product_category_name_translation' | Shape: (71, 2)

In [8]:
import pandas as pd

def convert_dataframe_numerics(df):
    """
    Attempts to convert each column in a DataFrame to numeric types (int/float).
    If a column contains non-numeric text, it is left untouched.
    """
    df_clean = df.copy()
    
    for col in df_clean.columns:
        # Try converting the entire column to numeric
        converted = pd.to_numeric(df_clean[col], errors='coerce')
        
        # If the column was originally non-null and conversion produced NO extra NaNs,
        # or if all non-null values were successfully converted, update the column.
        if converted.notna().sum() == df_clean[col].notna().sum() and df_clean[col].notna().sum() > 0:
            df_clean[col] = converted
            
    return df_clean

# --- APPLY TO ALL DATASETS IN GLOBAL MEMORY ---
for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame) and not name.startswith('_'):
        globals()[name] = convert_dataframe_numerics(obj)
        print(f"Updated column types for DataFrame: '{name}'")

Updated column types for DataFrame: 'master_orders_clean'
Updated column types for DataFrame: 'customers'
Updated column types for DataFrame: 'geolocation'
Updated column types for DataFrame: 'orders'
Updated column types for DataFrame: 'order_items'
Updated column types for DataFrame: 'order_payments'
Updated column types for DataFrame: 'order_reviews'
Updated column types for DataFrame: 'products'
Updated column types for DataFrame: 'sellers'
Updated column types for DataFrame: 'product_category_name_translation'

In [9]:
olist_datasets = [
    'customers', 'geolocation', 'orders', 'order_items', 
    'order_payments', 'order_reviews', 'products', 
    'sellers', 'product_category_name_translation'
]

for name in olist_datasets:
    if name in globals() and isinstance(globals()[name], pd.DataFrame):
        df = globals()[name]
        print(f"=== {name.upper()} ===")
        # Get nunique() specifically for object/string columns
        text_uniques = df.select_dtypes(include=['object', 'string']).nunique()
        
        if text_uniques.empty:
            print("  (No string/object columns found)")
        else:
            print(text_uniques)
        print("\n" + "-" * 40 + "\n")

=== CUSTOMERS ===
customer_id           99441
customer_unique_id    96096
customer_city          4119
customer_state           27
dtype: int64

----------------------------------------

=== GEOLOCATION ===
geolocation_city     8010
geolocation_state      27
dtype: int64

----------------------------------------

=== ORDERS ===
order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

----------------------------------------

=== ORDER_ITEMS ===
order_id               98666
product_id             32951
seller_id               3095
shipping_limit_date    93318
dtype: int64

----------------------------------------

=== ORDER_PAYMENTS ===
order_id        99440
payment_type        5
dtype: int64

----------------------------------------

=== ORDER_REVIEWS ===
review_id                  98410
order_id                   98673
review_comment_title        3679
review_comment_message     35007
review_creation_date         636
review_answer_timestamp    98248
dtype: int64

----------------------------------------

=== PRODUCTS ===
product_id               32951
product_category_name       73
dtype: int64

----------------------------------------

=== SELLERS ===
seller_id       3095
seller_city      611
seller_state      23
dtype: int64

----------------------------------------

=== PRODUCT_CATEGORY_NAME_TRANSLATION ===
product_category_name            71
product_category_name_english    71
dtype: int64

----------------------------------------

In [10]:
import pandas as pd

# Target only true categorical columns across your datasets
target_categorical_cols = {
    'products': ['product_category_name'],
    'product_category_name_translation': ['product_category_name', 'product_category_name_english'],
    'customers': ['customer_city', 'customer_state'],
    'sellers': ['seller_city', 'seller_state'],
    'geolocation': ['geolocation_city', 'geolocation_state'],
    'order_payments': ['payment_type'],
    'orders': ['order_status']
}

for df_name, cols in target_categorical_cols.items():
    if df_name in globals() and isinstance(globals()[df_name], pd.DataFrame):
        df = globals()[df_name]
        print(f"================ DATASET: {df_name.upper()} ================")
        
        for col in cols:
            if col in df.columns:
                print(f"\n--- VALUE COUNTS FOR: '{col}' (Total Unique: {df[col].nunique()}) ---")
                # Showing value counts sorted by frequency
                print(df[col].value_counts(dropna=False))
                print("-" * 50)
                
        print("\n" + "=" * 60 + "\n")

================ DATASET: PRODUCTS ================

--- VALUE COUNTS FOR: 'product_category_name' (Total Unique: 73) ---
product_category_name
Cama_Mesa_Banho                  3029
Esporte_Lazer                    2867
Moveis_Decoracao                 2657
Beleza_Saude                     2444
Utilidades_Domesticas            2335
                                 ...
Fashion_Roupa_Infanto_Juvenil       5
Casa_Conforto_2                     5
Pc_Gamer                            3
Seguros_E_Servicos                  2
Cds_Dvds_Musicais                   1
Name: count, Length: 74, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: PRODUCT_CATEGORY_NAME_TRANSLATION ================

--- VALUE COUNTS FOR: 'product_category_name' (Total Unique: 71) ---
product_category_name
Beleza_Saude                     1
Informatica_Acessorios           1
Automotivo                       1
Cama_Mesa_Banho                  1
Moveis_Decoracao                 1
                                ..
Flores                           1
Artes_E_Artesanato               1
Fraldas_Higiene                  1
Fashion_Roupa_Infanto_Juvenil    1
Seguros_E_Servicos               1
Name: count, Length: 71, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'product_category_name_english' (Total Unique: 71) ---
product_category_name_english
Health_Beauty                1
Computers_Accessories        1
Auto                         1
Bed_Bath_Table               1
Furniture_Decor              1
                            ..
Flowers                      1
Arts_And_Craftmanship        1
Diapers_And_Hygiene          1
Fashion_Childrens_Clothes    1
Security_And_Services        1
Name: count, Length: 71, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: CUSTOMERS ================

--- VALUE COUNTS FOR: 'customer_city' (Total Unique: 4119) ---
customer_city
Sao Paulo              15540
Rio De Janeiro          6882
Belo Horizonte          2773
Brasilia                2131
Curitiba                1521
                       ...
Siriji                     1
Natividade Da Serra        1
Monte Bonito               1
Sao Rafael                 1
Eugenio De Castro          1
Name: count, Length: 4119, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'customer_state' (Total Unique: 27) ---
customer_state
Sp    41746
Rj    12852
Mg    11635
Rs     5466
Pr     5045
Sc     3637
Ba     3380
Df     2140
Es     2033
Go     2020
Pe     1652
Ce     1336
Pa      975
Mt      907
Ma      747
Ms      715
Pb      536
Pi      495
Rn      485
Al      413
Se      350
To      280
Ro      253
Am      148
Ac       81
Ap       68
Rr       46
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: SELLERS ================

--- VALUE COUNTS FOR: 'seller_city' (Total Unique: 611) ---
seller_city
Sao Paulo                 694
Curitiba                  127
Rio De Janeiro             96
Belo Horizonte             68
Ribeirao Preto             52
                         ...
Aparecida De Goiania        1
Bandeirantes                1
Vitoria De Santo Antao      1
Palotina                    1
Leme                        1
Name: count, Length: 611, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'seller_state' (Total Unique: 23) ---
seller_state
Sp    1849
Pr     349
Mg     244
Sc     190
Rj     171
Rs     129
Go      40
Df      30
Es      23
Ba      19
Ce      13
Pe       9
Pb       6
Rn       5
Ms       5
Mt       4
Ro       2
Se       2
Ac       1
Pi       1
Ma       1
Am       1
Pa       1
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: GEOLOCATION ================

--- VALUE COUNTS FOR: 'geolocation_city' (Total Unique: 8010) ---
geolocation_city
Sao Paulo                     79927
Rio De Janeiro                35177
São Paulo                     19718
Belo Horizonte                19474
Curitiba                      11263
                              ...
Almirante Tamandaré Do Sul        1
Três Palmeiras                    1
São Valentim                      1
Três Arroios                      1
Ciríaco                           1
Name: count, Length: 8010, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'geolocation_state' (Total Unique: 27) ---
geolocation_state
Sp    285976
Mg    101353
Rj     78836
Rs     48093
Pr     45059
Sc     30191
Ba     27720
Go     15601
Pe     13162
Es     12632
Ce      9541
Mt      9374
Df      9080
Ms      8594
Pa      8551
Ma      6277
Pb      4787
Rn      4014
Pi      3592
Al      3415
To      2977
Se      2653
Ro      2523
Am      1986
Ac      1039
Ap       738
Rr       568
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: ORDER_PAYMENTS ================

--- VALUE COUNTS FOR: 'payment_type' (Total Unique: 5) ---
payment_type
Credit_Card    76795
Boleto         19784
Voucher         5775
Debit_Card      1529
Not_Defined        3
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: ORDERS ================

--- VALUE COUNTS FOR: 'order_status' (Total Unique: 8) ---
order_status
Delivered      96478
Shipped         1107
Canceled         625
Unavailable      609
Invoiced         314
Processing       301
Created            5
Approved           2
Name: count, dtype: int64
--------------------------------------------------

============================================================

In [11]:
import unicodedata

def normalize_text_accents(text):
    """
    Strips Portuguese accents (e.g., 'São' -> 'Sao') 
    and standardizes casing and extra whitespaces.
    """
    if not isinstance(text, str):
        return text
    
    # Decompose unicode characters to separate letters from accents
    nfkd_form = unicodedata.normalize('NFKD', text)
    # Rebuild string keeping only base ASCII letters
    clean_str = "".join([c for c in nfkd_form if not unicodedata.combining(c)])
    
    # Standardize spaces and apply title case
    return clean_str.strip().title()

# Map of city columns to clean across your loaded DataFrames
city_columns_to_fix = [
    ('customers', 'customer_city'),
    ('sellers', 'seller_city'),
    ('geolocation', 'geolocation_city')
]

# Apply accent normalization
for df_name, col in city_columns_to_fix:
    if df_name in globals():
        globals()[df_name][col] = globals()[df_name][col].apply(normalize_text_accents)
        print(f"Normalized city names in '{df_name}.{col}'")

Normalized city names in 'customers.customer_city'
Normalized city names in 'sellers.seller_city'
Normalized city names in 'geolocation.geolocation_city'

In [12]:
import pandas as pd

# Target only true categorical columns across your datasets
target_categorical_cols = {
    'products': ['product_category_name'],
    'product_category_name_translation': ['product_category_name', 'product_category_name_english'],
    'customers': ['customer_city', 'customer_state'],
    'sellers': ['seller_city', 'seller_state'],
    'geolocation': ['geolocation_city', 'geolocation_state'],
    'order_payments': ['payment_type'],
    'orders': ['order_status']
}

for df_name, cols in target_categorical_cols.items():
    if df_name in globals() and isinstance(globals()[df_name], pd.DataFrame):
        df = globals()[df_name]
        print(f"================ DATASET: {df_name.upper()} ================")
        
        for col in cols:
            if col in df.columns:
                print(f"\n--- VALUE COUNTS FOR: '{col}' (Total Unique: {df[col].nunique()}) ---")
                # Showing value counts sorted by frequency
                print(df[col].value_counts(dropna=False))
                print("-" * 50)
                
        print("\n" + "=" * 60 + "\n")

================ DATASET: PRODUCTS ================

--- VALUE COUNTS FOR: 'product_category_name' (Total Unique: 73) ---
product_category_name
Cama_Mesa_Banho                  3029
Esporte_Lazer                    2867
Moveis_Decoracao                 2657
Beleza_Saude                     2444
Utilidades_Domesticas            2335
                                 ...
Fashion_Roupa_Infanto_Juvenil       5
Casa_Conforto_2                     5
Pc_Gamer                            3
Seguros_E_Servicos                  2
Cds_Dvds_Musicais                   1
Name: count, Length: 74, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: PRODUCT_CATEGORY_NAME_TRANSLATION ================

--- VALUE COUNTS FOR: 'product_category_name' (Total Unique: 71) ---
product_category_name
Beleza_Saude                     1
Informatica_Acessorios           1
Automotivo                       1
Cama_Mesa_Banho                  1
Moveis_Decoracao                 1
                                ..
Flores                           1
Artes_E_Artesanato               1
Fraldas_Higiene                  1
Fashion_Roupa_Infanto_Juvenil    1
Seguros_E_Servicos               1
Name: count, Length: 71, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'product_category_name_english' (Total Unique: 71) ---
product_category_name_english
Health_Beauty                1
Computers_Accessories        1
Auto                         1
Bed_Bath_Table               1
Furniture_Decor              1
                            ..
Flowers                      1
Arts_And_Craftmanship        1
Diapers_And_Hygiene          1
Fashion_Childrens_Clothes    1
Security_And_Services        1
Name: count, Length: 71, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: CUSTOMERS ================

--- VALUE COUNTS FOR: 'customer_city' (Total Unique: 4119) ---
customer_city
Sao Paulo              15540
Rio De Janeiro          6882
Belo Horizonte          2773
Brasilia                2131
Curitiba                1521
                       ...
Siriji                     1
Natividade Da Serra        1
Monte Bonito               1
Sao Rafael                 1
Eugenio De Castro          1
Name: count, Length: 4119, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'customer_state' (Total Unique: 27) ---
customer_state
Sp    41746
Rj    12852
Mg    11635
Rs     5466
Pr     5045
Sc     3637
Ba     3380
Df     2140
Es     2033
Go     2020
Pe     1652
Ce     1336
Pa      975
Mt      907
Ma      747
Ms      715
Pb      536
Pi      495
Rn      485
Al      413
Se      350
To      280
Ro      253
Am      148
Ac       81
Ap       68
Rr       46
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: SELLERS ================

--- VALUE COUNTS FOR: 'seller_city' (Total Unique: 609) ---
seller_city
Sao Paulo                 695
Curitiba                  127
Rio De Janeiro             96
Belo Horizonte             68
Ribeirao Preto             52
                         ...
Aparecida De Goiania        1
Bandeirantes                1
Vitoria De Santo Antao      1
Palotina                    1
Leme                        1
Name: count, Length: 609, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'seller_state' (Total Unique: 23) ---
seller_state
Sp    1849
Pr     349
Mg     244
Sc     190
Rj     171
Rs     129
Go      40
Df      30
Es      23
Ba      19
Ce      13
Pe       9
Pb       6
Rn       5
Ms       5
Mt       4
Ro       2
Se       2
Ac       1
Pi       1
Ma       1
Am       1
Pa       1
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: GEOLOCATION ================

--- VALUE COUNTS FOR: 'geolocation_city' (Total Unique: 5967) ---
geolocation_city
Sao Paulo           99645
Rio De Janeiro      35177
Belo Horizonte      19474
Curitiba            11263
Brasilia             8791
                    ...
Barrado Quarai          1
Rolador                 1
Sete De Setembro        1
Lajeado Do Bugre        1
Padre Gonzales          1
Name: count, Length: 5967, dtype: int64
--------------------------------------------------

--- VALUE COUNTS FOR: 'geolocation_state' (Total Unique: 27) ---
geolocation_state
Sp    285976
Mg    101353
Rj     78836
Rs     48093
Pr     45059
Sc     30191
Ba     27720
Go     15601
Pe     13162
Es     12632
Ce      9541
Mt      9374
Df      9080
Ms      8594
Pa      8551
Ma      6277
Pb      4787
Rn      4014
Pi      3592
Al      3415
To      2977
Se      2653
Ro      2523
Am      1986
Ac      1039
Ap       738
Rr       568
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: ORDER_PAYMENTS ================

--- VALUE COUNTS FOR: 'payment_type' (Total Unique: 5) ---
payment_type
Credit_Card    76795
Boleto         19784
Voucher         5775
Debit_Card      1529
Not_Defined        3
Name: count, dtype: int64
--------------------------------------------------

============================================================

================ DATASET: ORDERS ================

--- VALUE COUNTS FOR: 'order_status' (Total Unique: 8) ---
order_status
Delivered      96478
Shipped         1107
Canceled         625
Unavailable      609
Invoiced         314
Processing       301
Created            5
Approved           2
Name: count, dtype: int64
--------------------------------------------------

============================================================

In [13]:
import pandas as pd

olist_datasets = [
    'customers', 'geolocation', 'orders', 'order_items', 
    'order_payments', 'order_reviews', 'products', 
    'sellers', 'product_category_name_translation'
]

print("=== NUMERIC COLUMNS WITH LESS THAN 10 UNIQUE VALUE IT IS ALSO CATEGORIAL VALUES===\n")

for name in olist_datasets:
    if name in globals() and isinstance(globals()[name], pd.DataFrame):
        df = globals()[name]
        
        # Select numeric columns (int64, float64, etc.)
        numeric_cols = df.select_dtypes(include=['number']).columns
        
        found_any = False
        for col in numeric_cols:
            n_unique = df[col].nunique(dropna=False)
            
            # Filter for columns with less than 10 unique values
            if n_unique < 10:
                if not found_any:
                    print(f"================ DATASET: {name.upper()} ================")
                    found_any = True
                
                print(f"\n--- Column: '{col}' ({n_unique} unique values) ---")
                print("Unique Values:", sorted(df[col].dropna().unique().tolist()))
                print("\nValue Counts:")
                print(df[col].value_counts(dropna=False))
                print("-" * 50)
                
        if found_any:
            print("\n" + "=" * 60 + "\n")

=== NUMERIC COLUMNS WITH LESS THAN 10 UNIQUE VALUE IT IS ALSO CATEGORIAL VALUES===

================ DATASET: ORDER_REVIEWS ================

--- Column: 'review_score' (5 unique values) ---
Unique Values: [1, 2, 3, 4, 5]

Value Counts:
review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64
--------------------------------------------------

============================================================

In [14]:
import numpy as np
import pandas as pd

# 1. Map columns that MUST be strictly non-negative (>= 0)
non_negative_schema = {
    'order_items': ['price', 'freight_value', 'order_item_id'],
    'order_payments': ['payment_value', 'payment_sequential', 'payment_installments'],
    'order_reviews': ['review_score'],
    'products': [
        'product_photos_qty', 'product_name_lenght', 'product_description_lenght',
        'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm'
    ]
}

# 2. Define columns where negative numbers ARE allowed (geographical coordinates in Brazil)
valid_negative_schema = {
    'geolocation': ['geolocation_lat', 'geolocation_lng']
}

print("=== DETECTION & CLEANING OF INVALID NEGATIVE VALUES ===\n")

total_negatives_cleaned = 0

# Scan non-negative target columns
for df_name, columns in non_negative_schema.items():
    if df_name in globals() and isinstance(globals()[df_name], pd.DataFrame):
        df = globals()[df_name]
        
        for col in columns:
            if col in df.columns:
                # Detect negative numbers (< 0)
                neg_mask = df[col] < 0
                neg_count = neg_mask.sum()
                
                if neg_count > 0:
                    total_negatives_cleaned += neg_count
                    print(f"⚠️ DETECTED: {neg_count} invalid negative value(s) in '{df_name}.{col}'")
                    # Replace invalid negatives with NaN
                    df.loc[neg_mask, col] = np.nan
                    print(f"   ↳ Cleaned: Replaced negative values in '{df_name}.{col}' with NaN.")
                else:
                    print(f"✅ CLEAN: '{df_name}.{col}' has 0 negative values.")

print("\n" + "="*60)
print("=== PRESERVED COLUMNS (WHERE NEGATIVES ARE VALID) ===")

# Verify coordinate columns stay untouched
for df_name, columns in valid_negative_schema.items():
    if df_name in globals() and isinstance(globals()[df_name], pd.DataFrame):
        df = globals()[df_name]
        for col in columns:
            if col in df.columns:
                neg_count = (df[col] < 0).sum()
                print(f"📍 '{df_name}.{col}' contains {neg_count:,} valid negative coordinates (LEFT UNTOUCHED).")

print("="*60)
if total_negatives_cleaned == 0:
    print("🎉 RESULT: No invalid negative values were found in your data!")
else:
    print(f"🎉 RESULT: Successfully removed {total_negatives_cleaned} invalid negative value(s).")

=== DETECTION & CLEANING OF INVALID NEGATIVE VALUES ===

✅ CLEAN: 'order_items.price' has 0 negative values.
✅ CLEAN: 'order_items.freight_value' has 0 negative values.
✅ CLEAN: 'order_items.order_item_id' has 0 negative values.
✅ CLEAN: 'order_payments.payment_value' has 0 negative values.
✅ CLEAN: 'order_payments.payment_sequential' has 0 negative values.
✅ CLEAN: 'order_payments.payment_installments' has 0 negative values.
✅ CLEAN: 'order_reviews.review_score' has 0 negative values.
✅ CLEAN: 'products.product_photos_qty' has 0 negative values.
✅ CLEAN: 'products.product_name_lenght' has 0 negative values.
✅ CLEAN: 'products.product_description_lenght' has 0 negative values.
✅ CLEAN: 'products.product_weight_g' has 0 negative values.
✅ CLEAN: 'products.product_length_cm' has 0 negative values.
✅ CLEAN: 'products.product_height_cm' has 0 negative values.
✅ CLEAN: 'products.product_width_cm' has 0 negative values.

============================================================
=== PRESERVED COLUMNS (WHERE NEGATIVES ARE VALID) ===
📍 'geolocation.geolocation_lat' contains 737,161 valid negative coordinates (LEFT UNTOUCHED).
📍 'geolocation.geolocation_lng' contains 738,329 valid negative coordinates (LEFT UNTOUCHED).
============================================================
🎉 RESULT: No invalid negative values were found in your data!

In [15]:
import pandas as pd

# List of your 9 Olist dataset names
olist_datasets = [
    'customers', 'geolocation', 'orders', 'order_items', 
    'order_payments', 'order_reviews', 'products', 'sellers', 
    'product_category_name_translation'
]

# Summary list to collect missing data info
missing_summary = []

for name in olist_datasets:
    if name in globals() and isinstance(globals()[name], pd.DataFrame):
        df = globals()[name]
        total_rows = len(df)
        
        # Calculate missing counts and percentages per column
        missing_count = df.isna().sum()
        missing_percent = (missing_count / total_rows) * 100
        
        for col in df.columns:
            if missing_count[col] > 0:  # Only report columns that have missing values
                missing_summary.append({
                    'DataFrame': name,
                    'Column': col,
                    'Missing Count': missing_count[col],
                    'Total Rows': total_rows,
                    'Missing (%)': round(missing_percent[col], 2)
                })

# Convert to DataFrame for a clean view
missing_df = pd.DataFrame(missing_summary)

if missing_df.empty:
    print("No missing values found across any of the datasets!")
else:
    print(missing_df.to_string(index=False))

    DataFrame                        Column  Missing Count  Total Rows  Missing (%)
       orders             order_approved_at            160       99441         0.16
       orders  order_delivered_carrier_date           1783       99441         1.79
       orders order_delivered_customer_date           2965       99441         2.98
order_reviews          review_comment_title          87656       99224        88.34
order_reviews        review_comment_message          58247       99224        58.70
     products         product_category_name            610       32951         1.85
     products           product_name_lenght            610       32951         1.85
     products    product_description_lenght            610       32951         1.85
     products            product_photos_qty            610       32951         1.85
     products              product_weight_g              2       32951         0.01
     products             product_length_cm              2       32951         0.01
     products             product_height_cm              2       32951         0.01
     products              product_width_cm              2       32951         0.01

In [16]:
(order_reviews.isnull().sum() / len(order_reviews)) * 100

review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [17]:
import pandas as pd

olist_datasets = [
    'customers', 'geolocation', 'orders', 'order_items', 
    'order_payments', 'order_reviews', 'products', 'sellers', 
    'product_category_name_translation'
]

for name in olist_datasets:
    if name in globals() and isinstance(globals()[name], pd.DataFrame):
        df = globals()[name]
        print(f"================ {name.upper()} ================")
        missing_pct = (df.isnull().sum() / len(df)) * 100
        # Print columns that have missing values (or print all if you prefer)
        print(missing_pct[missing_pct > 0].round(2))
        print("\n")

================ CUSTOMERS ================
Series([], dtype: float64)


================ GEOLOCATION ================
Series([], dtype: float64)


================ ORDERS ================
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
dtype: float64


================ ORDER_ITEMS ================
Series([], dtype: float64)


================ ORDER_PAYMENTS ================
Series([], dtype: float64)


================ ORDER_REVIEWS ================
review_comment_title      88.34
review_comment_message    58.70
dtype: float64


================ PRODUCTS ================
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64


================ SELLERS ================
Series([], dtype: float64)


================ PRODUCT_CATEGORY_NAME_TRANSLATION ================
Series([], dtype: float64)

In [18]:
# Clean way to fill NaNs without ChainedAssignmentError
order_reviews['review_comment_title'] = order_reviews['review_comment_title'].fillna('No Title')
order_reviews['review_comment_message'] = order_reviews['review_comment_message'].fillna('No Comment')

In [19]:
import pandas as pd

# Create a clean summary table for order_reviews
col_summary = pd.DataFrame({
    'Column Name': order_reviews.columns,
    'Row Count (Non-Null)': order_reviews.count().values,
    'Total Rows': len(order_reviews)
})

col_summary

               Column Name  Row Count (Non-Null)  Total Rows
0                review_id                 99224       99224
1                 order_id                 99224       99224
2             review_score                 99224       99224
3     review_comment_title                 99224       99224
4   review_comment_message                 99224       99224
5     review_creation_date                 99224       99224
6  review_answer_timestamp                 99224       99224

In [20]:
# Drop all rows that have missing values in the products DataFrame
products.dropna(inplace=True)

# Verify that there are 0 missing values left across all columns
print("Remaining missing values in products:")
print(products.isnull().sum())
print(f"\nNew products DataFrame shape: {products.shape}")

Remaining missing values in products:
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

New products DataFrame shape: (32340, 9)

In [21]:
products.loc[
    products["product_category_name"].isna(),
    [
        "product_category_name",
        "product_name_lenght",
        "product_description_lenght",
        "product_photos_qty"
    ]
]

Empty DataFrame
Columns: [product_category_name, product_name_lenght, product_description_lenght, product_photos_qty]
Index: []

In [22]:
orders.groupby("order_status")[
    [
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].apply(lambda x: x.isna().mean() * 100)

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
Approved,0.000000,100.000000,100.000000
Canceled,22.560000,88.000000,99.040000
Created,100.000000,100.000000,100.000000
Delivered,0.014511,0.002073,0.008292
Invoiced,0.000000,100.000000,100.000000
Processing,0.000000,100.000000,100.000000
Shipped,0.000000,0.000000,100.000000
Unavailable,0.000000,100.000000,100.000000

In [23]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        print(f"================ {name.upper()} ================")
        df.info()
        print("\n")

================ DF ================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB


================ MASTER_ORDERS_CLEAN ================
<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  str
 14  seller_id                      118310 non-null  str
 15  shipping_limit_date            118310 non-null  str
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116600 non-null  str
 19  product_name_lenght            116600 non-null  float64
 20  product_description_lenght     116600 non-null  float64
 21  product_photos_qty             116600 non-null  float64
 22  product_weight_g               116600 non-null  float64
 23  product_length_cm              116600 non-null  float64
 24  product_height_cm              116600 non-null  float64
 25  product_width_cm               116600 non-null  float64
 26  product_category_name_english  116575 non-null  str
 27  seller_zip_code_prefix         118310 non-null  float64
 28  seller_city                    118310 non-null  str
 29  seller_state                   118310 non-null  str
 30  payment_sequential             119140 non-null  float64
 31  payment_type                   119140 non-null  str
 32  payment_installments           119140 non-null  float64
 33  payment_value                  119140 non-null  float64
 34  review_id                      118146 non-null  str
 35  review_score                   118146 non-null  float64
 36  review_comment_title           118144 non-null  str
 37  review_comment_message         118114 non-null  str
 38  review_creation_date           118146 non-null  str
 39  review_answer_timestamp        118146 non-null  str
dtypes: float64(15), int64(1), str(24)
memory usage: 36.4 MB


================ CUSTOMERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB


================ GEOLOCATION ================
<class 'pandas.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  int64
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  str
 4   geolocation_state            738332 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 33.8 MB


================ ORDERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB


================ ORDER_ITEMS ================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB


================ ORDER_PAYMENTS ================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB


================ ORDER_REVIEWS ================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB


================ PRODUCTS ================
<class 'pandas.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  str
 1   product_category_name       32340 non-null  str
 2   product_name_lenght         32340 non-null  float64
 3   product_description_lenght  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.5 MB


================ SELLERS ================
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB


================ PRODUCT_CATEGORY_NAME_TRANSLATION ================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB


================ MISSING_DF ================
<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DataFrame      13 non-null     str
 1   Column         13 non-null     str
 2   Missing Count  13 non-null     int64
 3   Total Rows     13 non-null     int64
 4   Missing (%)    13 non-null     float64
dtypes: float64(1), int64(2), str(2)
memory usage: 652.0 bytes


================ COL_SUMMARY ================
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Column Name           7 non-null      str
 1   Row Count (Non-Null)  7 non-null      int64
 2   Total Rows            7 non-null      int64
dtypes: int64(2), str(1)
memory usage: 300.0 bytes

In [24]:
# List of dataframes to remove
dfs_to_remove = ['df', 'col_summary', 'missing_df']

for name in dfs_to_remove:
    if name in globals():
        del globals()[name]
        print(f"Successfully deleted DataFrame: '{name}'")

Successfully deleted DataFrame: 'df'
Successfully deleted DataFrame: 'col_summary'
Successfully deleted DataFrame: 'missing_df'

In [25]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        print(f"================ {name.upper()} ================")
        df.info()
        print("\n")

================ MASTER_ORDERS_CLEAN ================
<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  str
 14  seller_id                      118310 non-null  str
 15  shipping_limit_date            118310 non-null  str
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116600 non-null  str
 19  product_name_lenght            116600 non-null  float64
 20  product_description_lenght     116600 non-null  float64
 21  product_photos_qty             116600 non-null  float64
 22  product_weight_g               116600 non-null  float64
 23  product_length_cm              116600 non-null  float64
 24  product_height_cm              116600 non-null  float64
 25  product_width_cm               116600 non-null  float64
 26  product_category_name_english  116575 non-null  str
 27  seller_zip_code_prefix         118310 non-null  float64
 28  seller_city                    118310 non-null  str
 29  seller_state                   118310 non-null  str
 30  payment_sequential             119140 non-null  float64
 31  payment_type                   119140 non-null  str
 32  payment_installments           119140 non-null  float64
 33  payment_value                  119140 non-null  float64
 34  review_id                      118146 non-null  str
 35  review_score                   118146 non-null  float64
 36  review_comment_title           118144 non-null  str
 37  review_comment_message         118114 non-null  str
 38  review_creation_date           118146 non-null  str
 39  review_answer_timestamp        118146 non-null  str
dtypes: float64(15), int64(1), str(24)
memory usage: 36.4 MB


================ CUSTOMERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB


================ GEOLOCATION ================
<class 'pandas.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  int64
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  str
 4   geolocation_state            738332 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 33.8 MB


================ ORDERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB


================ ORDER_ITEMS ================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB


================ ORDER_PAYMENTS ================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB


================ ORDER_REVIEWS ================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB


================ PRODUCTS ================
<class 'pandas.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  str
 1   product_category_name       32340 non-null  str
 2   product_name_lenght         32340 non-null  float64
 3   product_description_lenght  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.5 MB


================ SELLERS ================
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB


================ PRODUCT_CATEGORY_NAME_TRANSLATION ================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [26]:
from sqlalchemy import create_engine

# ----------------------------------------------------------------------
# ✏️ UPDATE YOUR MYSQL PASSWORD HERE
# ----------------------------------------------------------------------
username = 'root'                # Default MySQL user
password = 'ak4776239' # Replace with your Workbench password
host = 'localhost'
port = '3306'
database = 'olist_db'            # The database we created in Step 2

# 1. Create connection to MySQL
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# 2. Put all your DataFrames in a dictionary
tables = {
    'customers': customers,
    'orders': orders,
    'order_items': order_items,
    'order_payments': order_payments,
    'order_reviews': order_reviews,
    'products': products,
    'sellers': sellers,
    'geolocation': geolocation,
    'product_category_name_translation': product_category_name_translation
}

# 3. Upload every table automatically
for table_name, df in tables.items():
    print(f"Uploading '{table_name}'...")
    df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)
    print(f"✅ Created table: {table_name}")

print("\n🎉 All tables uploaded successfully to MySQL Workbench!")

Uploading 'customers'...
✅ Created table: customers
Uploading 'orders'...
✅ Created table: orders
Uploading 'order_items'...
✅ Created table: order_items
Uploading 'order_payments'...
✅ Created table: order_payments
Uploading 'order_reviews'...
✅ Created table: order_reviews
Uploading 'products'...
✅ Created table: products
Uploading 'sellers'...
✅ Created table: sellers
Uploading 'geolocation'...
✅ Created table: geolocation
Uploading 'product_category_name_translation'...
✅ Created table: product_category_name_translation

🎉 All tables uploaded successfully to MySQL Workbench!

In [27]:
if 'df' in globals():
    del df
    print("Variable 'df' successfully removed.")

Variable 'df' successfully removed.

In [28]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        print(f"================ {name.upper()} ================")
        df.info()
        print("\n")

================ MASTER_ORDERS_CLEAN ================
<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  str
 14  seller_id                      118310 non-null  str
 15  shipping_limit_date            118310 non-null  str
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116600 non-null  str
 19  product_name_lenght            116600 non-null  float64
 20  product_description_lenght     116600 non-null  float64
 21  product_photos_qty             116600 non-null  float64
 22  product_weight_g               116600 non-null  float64
 23  product_length_cm              116600 non-null  float64
 24  product_height_cm              116600 non-null  float64
 25  product_width_cm               116600 non-null  float64
 26  product_category_name_english  116575 non-null  str
 27  seller_zip_code_prefix         118310 non-null  float64
 28  seller_city                    118310 non-null  str
 29  seller_state                   118310 non-null  str
 30  payment_sequential             119140 non-null  float64
 31  payment_type                   119140 non-null  str
 32  payment_installments           119140 non-null  float64
 33  payment_value                  119140 non-null  float64
 34  review_id                      118146 non-null  str
 35  review_score                   118146 non-null  float64
 36  review_comment_title           118144 non-null  str
 37  review_comment_message         118114 non-null  str
 38  review_creation_date           118146 non-null  str
 39  review_answer_timestamp        118146 non-null  str
dtypes: float64(15), int64(1), str(24)
memory usage: 36.4 MB


================ CUSTOMERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB


================ GEOLOCATION ================
<class 'pandas.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  int64
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  str
 4   geolocation_state            738332 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 33.8 MB


================ ORDERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB


================ ORDER_ITEMS ================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB


================ ORDER_PAYMENTS ================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB


================ ORDER_REVIEWS ================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB


================ PRODUCTS ================
<class 'pandas.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  str
 1   product_category_name       32340 non-null  str
 2   product_name_lenght         32340 non-null  float64
 3   product_description_lenght  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.5 MB


================ SELLERS ================
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB


================ PRODUCT_CATEGORY_NAME_TRANSLATION ================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [29]:
import pandas as pd

# Map out the date/timestamp columns for each DataFrame
date_columns_map = {
    'orders': [
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date'
    ],
    'order_items': [
        'shipping_limit_date'
    ],
    'order_reviews': [
        'review_creation_date',
        'review_answer_timestamp'
    ]
}

# Convert specified columns to datetime
for df_name, date_cols in date_columns_map.items():
    if df_name in globals() and isinstance(globals()[df_name], pd.DataFrame):
        df = globals()[df_name]
        for col in date_cols:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors='coerce')
        print(f"Successfully converted date columns in '{df_name}'.")

# Quick check on the orders DataFrame to confirm data types
orders.dtypes

Successfully converted date columns in 'orders'.
Successfully converted date columns in 'order_items'.
Successfully converted date columns in 'order_reviews'.

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [30]:
# Check data types for order_items
print("=== ORDER_ITEMS DTYPES ===")
print(order_items.dtypes)

# Check data types for order_reviews
print("\n=== ORDER_REVIEWS DTYPES ===")
print(order_reviews.dtypes)

=== ORDER_ITEMS DTYPES ===
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

=== ORDER_REVIEWS DTYPES ===
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [31]:
import numpy as np
import pandas as pd

# 1. Replace empty strings or whitespace across all columns with NaN
orders.replace(r'^\s*$', np.nan, regex=True, inplace=True)

# 2. Re-enforce datetime format on date columns so missing values cleanly become NaT
date_cols = [
    'order_purchase_timestamp', 'order_approved_at', 
    'order_delivered_carrier_date', 'order_delivered_customer_date', 
    'order_estimated_delivery_date'
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors='coerce')

In [32]:
for name, df in list(globals().items()):
    if isinstance(df, pd.DataFrame) and not name.startswith('_'):
        print(f"================ {name.upper()} ================")
        df.info()
        print("\n")

================ MASTER_ORDERS_CLEAN ================
<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  str
 14  seller_id                      118310 non-null  str
 15  shipping_limit_date            118310 non-null  str
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116600 non-null  str
 19  product_name_lenght            116600 non-null  float64
 20  product_description_lenght     116600 non-null  float64
 21  product_photos_qty             116600 non-null  float64
 22  product_weight_g               116600 non-null  float64
 23  product_length_cm              116600 non-null  float64
 24  product_height_cm              116600 non-null  float64
 25  product_width_cm               116600 non-null  float64
 26  product_category_name_english  116575 non-null  str
 27  seller_zip_code_prefix         118310 non-null  float64
 28  seller_city                    118310 non-null  str
 29  seller_state                   118310 non-null  str
 30  payment_sequential             119140 non-null  float64
 31  payment_type                   119140 non-null  str
 32  payment_installments           119140 non-null  float64
 33  payment_value                  119140 non-null  float64
 34  review_id                      118146 non-null  str
 35  review_score                   118146 non-null  float64
 36  review_comment_title           118144 non-null  str
 37  review_comment_message         118114 non-null  str
 38  review_creation_date           118146 non-null  str
 39  review_answer_timestamp        118146 non-null  str
dtypes: float64(15), int64(1), str(24)
memory usage: 36.4 MB


================ CUSTOMERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB


================ GEOLOCATION ================
<class 'pandas.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  int64
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  str
 4   geolocation_state            738332 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 33.8 MB


================ ORDERS ================
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB


================ ORDER_ITEMS ================
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB


================ ORDER_PAYMENTS ================
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB


================ ORDER_REVIEWS ================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB


================ PRODUCTS ================
<class 'pandas.DataFrame'>
Index: 32340 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  str
 1   product_category_name       32340 non-null  str
 2   product_name_lenght         32340 non-null  float64
 3   product_description_lenght  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.5 MB


================ SELLERS ================
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB


================ PRODUCT_CATEGORY_NAME_TRANSLATION ================
<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB


================ DF ================
<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  str
 4   review_comment_message   99224 non-null  str
 5   review_creation_date     99224 non-null  datetime64[us]
 6   review_answer_timestamp  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 5.3 MB

In [33]:
# Display rows where the date is explicitly missing (NaT)
missing_carrier_dates = orders[orders['order_delivered_carrier_date'].isna()]
missing_carrier_dates[['order_id', 'order_status', 'order_delivered_carrier_date']].head()

,order_id,order_status,order_delivered_carrier_date
6,136Cce7Faa42Fdb2Cefd53Fdc79A6098,Invoiced,NaT
103,0760A852E4E9D89Eb77Bf631Eaaf1C84,Invoiced,NaT
128,15Bed8E2Fec7Fdbadb186B57C46C92F2,Processing,NaT
266,8E24261A7E58791D10Cb1Bf9Da94Df5C,Unavailable,NaT
324,D3C8851A6651Eeff2F73B0E011Ac45D0,Processing,NaT

In [34]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Join all tables step-by-step in Pandas
master_df = (
    orders
    .merge(customers, on='customer_id', how='left')
    .merge(order_items, on='order_id', how='left')
    .merge(products, on='product_id', how='left')
    .merge(product_category_name_translation, on='product_category_name', how='left')
    .merge(sellers, on='seller_id', how='left')
    .merge(order_payments, on='order_id', how='left')
    .merge(order_reviews, on='order_id', how='left')
)

print(f"Master dataset created with shape: {master_df.shape}")

# Option A: Export directly to SQL Database (Replace with your database connection details)
# engine = create_engine('sqlite:///olist_database.db')  # For SQLite
# engine = create_engine('mysql+pymysql://user:password@localhost/dbname')  # For MySQL
# master_df.to_sql('master_orders', con=engine, if_exists='replace', index=False)

# Option B: Export as a single CSV file to import into SQL
master_df.to_csv(r'C:\Users\Dell\Documents\download sql\master_orders_clean.csv', index=False, na_rep='')
print("Exported master_orders_clean.csv successfully!")

Master dataset created with shape: (119143, 40)
Exported master_orders_clean.csv successfully!

In [35]:
master_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,E481F51Cbdc54678B7Cc49136F2D6Af7,9Ef432Eb6251297304E76186B10A928D,Delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7C396Fd4830Fd04220F754E42B4E5Bff,3149,...,1.0,Credit_Card,1.0,18.12,A54F0611Adc9Ed256B57Ede6B6Eb5114,4.0,No Title,"Não Testei O Produto Ainda, Mas Ele Veio Corre...",2017-10-11,2017-10-12 03:43:48
1,E481F51Cbdc54678B7Cc49136F2D6Af7,9Ef432Eb6251297304E76186B10A928D,Delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7C396Fd4830Fd04220F754E42B4E5Bff,3149,...,3.0,Voucher,1.0,2.00,A54F0611Adc9Ed256B57Ede6B6Eb5114,4.0,No Title,"Não Testei O Produto Ainda, Mas Ele Veio Corre...",2017-10-11,2017-10-12 03:43:48
2,E481F51Cbdc54678B7Cc49136F2D6Af7,9Ef432Eb6251297304E76186B10A928D,Delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7C396Fd4830Fd04220F754E42B4E5Bff,3149,...,2.0,Voucher,1.0,18.59,A54F0611Adc9Ed256B57Ede6B6Eb5114,4.0,No Title,"Não Testei O Produto Ainda, Mas Ele Veio Corre...",2017-10-11,2017-10-12 03:43:48
3,53Cdb2Fc8Bc7Dce0B6741E2150273451,B0830Fb4747A6C6D20Dea0B8C802D7Ef,Delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,Af07308B275D755C9Edb36A90C618231,47813,...,1.0,Boleto,1.0,141.46,8D5266042046A06655C8Db133D120Ba5,4.0,Muito Boa A Loja,Muito Bom O Produto.,2018-08-08,2018-08-08 18:37:50
4,47770Eb9100C2D0C44946D9Cf07Ec65D,41Ce2A54C0B03Bf3443C3D931A367089,Delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3A653A41F6F9Fc3D2A113Cf8398680E8,75265,...,1.0,Credit_Card,3.0,179.12,E73B67B67587F7644D5Bd1A52Deb1B01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58

In [36]:
pd.set_option('display.max_columns', None)
master_df.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,seller_zip_code_prefix,seller_city,seller_state,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,E481F51Cbdc54678B7Cc49136F2D6Af7,9Ef432Eb6251297304E76186B10A928D,Delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7C396Fd4830Fd04220F754E42B4E5Bff,3149,Sao Paulo,Sp,1.0,87285B34884572647811A353C7Ac498A,3504C0Cb71D7Fa48D967E0E4C94D59D9,2017-10-06 11:07:15,29.99,8.72,Utilidades_Domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,Housewares,9350.0,Maua,Sp,1.0,Credit_Card,1.0,18.12,A54F0611Adc9Ed256B57Ede6B6Eb5114,4.0,No Title,"Não Testei O Produto Ainda, Mas Ele Veio Corre...",2017-10-11,2017-10-12 03:43:48
1,E481F51Cbdc54678B7Cc49136F2D6Af7,9Ef432Eb6251297304E76186B10A928D,Delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7C396Fd4830Fd04220F754E42B4E5Bff,3149,Sao Paulo,Sp,1.0,87285B34884572647811A353C7Ac498A,3504C0Cb71D7Fa48D967E0E4C94D59D9,2017-10-06 11:07:15,29.99,8.72,Utilidades_Domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,Housewares,9350.0,Maua,Sp,3.0,Voucher,1.0,2.00,A54F0611Adc9Ed256B57Ede6B6Eb5114,4.0,No Title,"Não Testei O Produto Ainda, Mas Ele Veio Corre...",2017-10-11,2017-10-12 03:43:48
2,E481F51Cbdc54678B7Cc49136F2D6Af7,9Ef432Eb6251297304E76186B10A928D,Delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7C396Fd4830Fd04220F754E42B4E5Bff,3149,Sao Paulo,Sp,1.0,87285B34884572647811A353C7Ac498A,3504C0Cb71D7Fa48D967E0E4C94D59D9,2017-10-06 11:07:15,29.99,8.72,Utilidades_Domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,Housewares,9350.0,Maua,Sp,2.0,Voucher,1.0,18.59,A54F0611Adc9Ed256B57Ede6B6Eb5114,4.0,No Title,"Não Testei O Produto Ainda, Mas Ele Veio Corre...",2017-10-11,2017-10-12 03:43:48
3,53Cdb2Fc8Bc7Dce0B6741E2150273451,B0830Fb4747A6C6D20Dea0B8C802D7Ef,Delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,Af07308B275D755C9Edb36A90C618231,47813,Barreiras,Ba,1.0,595Fac2A385Ac33A80Bd5114Aec74Eb8,289Cdb325Fb7E7F891C38608Bf9E0962,2018-07-30 03:24:27,118.70,22.76,Perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,Perfumery,31570.0,Belo Horizonte,Sp,1.0,Boleto,1.0,141.46,8D5266042046A06655C8Db133D120Ba5,4.0,Muito Boa A Loja,Muito Bom O Produto.,2018-08-08,2018-08-08 18:37:50
4,47770Eb9100C2D0C44946D9Cf07Ec65D,41Ce2A54C0B03Bf3443C3D931A367089,Delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3A653A41F6F9Fc3D2A113Cf8398680E8,75265,Vianopolis,Go,1.0,Aa4383B373C6Aca5D8797843E5594415,4869F7A5Dfa277A7Dca6462Dcf3B52B2,2018-08-13 08:55:23,159.90,19.22,Automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,Auto,14840.0,Guariba,Sp,1.0,Credit_Card,3.0,179.12,E73B67B67587F7644D5Bd1A52Deb1B01,5.0,No Title,No Comment,2018-08-18,2018-08-22 19:07:58

In [37]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ak4776239@localhost:3306/olist_db"
)

In [38]:
# 1. Create the merged master DataFrame
master_df = (
    orders
    .merge(customers, on='customer_id', how='left')
    .merge(order_items, on='order_id', how='left')
    .merge(products, on='product_id', how='left')
    .merge(product_category_name_translation, on='product_category_name', how='left')
    .merge(sellers, on='seller_id', how='left')
    .merge(order_payments, on='order_id', how='left')
    .merge(order_reviews, on='order_id', how='left')
)

# 2. Send it to MySQL using your engine variable
master_df.to_sql(
    name="master_df", 
    con=engine, 
    if_exists="replace", 
    index=False, 
    chunksize=10000
)

print("Uploaded successfully to MySQL!")

Uploaded successfully to MySQL!

In [39]:
master_df.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
customer_unique_id                          str
customer_zip_code_prefix                  int64
customer_city                               str
customer_state                              str
order_item_id                           float64
product_id                                  str
seller_id                                   str
shipping_limit_date              datetime64[us]
price                                   float64
freight_value                           float64
product_category_name                       str
product_name_lenght                     float64
product_description_lenght              float64
product_photos_qty                      float64
product_weight_g                        float64
product_length_cm                       float64
product_height_cm                       float64
product_width_cm                        float64
product_category_name_english               str
seller_zip_code_prefix                  float64
seller_city                                 str
seller_state                                str
payment_sequential                      float64
payment_type                                str
payment_installments                    float64
payment_value                           float64
review_id                                   str
review_score                            float64
review_comment_title                        str
review_comment_message                      str
review_creation_date             datetime64[us]
review_answer_timestamp          datetime64[us]
dtype: object

In [40]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [41]:
# Permanently clean master_df and save to Desktop as CSV
master_df = master_df.dropna()
master_df.to_csv(r'C:\Users\Dell\Desktop\master_df_cleaned.csv', index=False)

In [42]:
# Check total rows and columns
print("Rows and Columns:", master_df.shape)

# Detailed dataset info
master_df.info()

Rows and Columns: (113193, 40)
<class 'pandas.DataFrame'>
Index: 113193 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       113193 non-null  str
 1   customer_id                    113193 non-null  str
 2   order_status                   113193 non-null  str
 3   order_purchase_timestamp       113193 non-null  datetime64[us]
 4   order_approved_at              113193 non-null  datetime64[us]
 5   order_delivered_carrier_date   113193 non-null  datetime64[us]
 6   order_delivered_customer_date  113193 non-null  datetime64[us]
 7   order_estimated_delivery_date  113193 non-null  datetime64[us]
 8   customer_unique_id             113193 non-null  str
 9   customer_zip_code_prefix       113193 non-null  int64
 10  customer_city                  113193 non-null  str
 11  customer_state                 113193 non-null  str
 12  order_item_id                  113193 non-null  float64
 13  product_id                     113193 non-null  str
 14  seller_id                      113193 non-null  str
 15  shipping_limit_date            113193 non-null  datetime64[us]
 16  price                          113193 non-null  float64
 17  freight_value                  113193 non-null  float64
 18  product_category_name          113193 non-null  str
 19  product_name_lenght            113193 non-null  float64
 20  product_description_lenght     113193 non-null  float64
 21  product_photos_qty             113193 non-null  float64
 22  product_weight_g               113193 non-null  float64
 23  product_length_cm              113193 non-null  float64
 24  product_height_cm              113193 non-null  float64
 25  product_width_cm               113193 non-null  float64
 26  product_category_name_english  113193 non-null  str
 27  seller_zip_code_prefix         113193 non-null  float64
 28  seller_city                    113193 non-null  str
 29  seller_state                   113193 non-null  str
 30  payment_sequential             113193 non-null  float64
 31  payment_type                   113193 non-null  str
 32  payment_installments           113193 non-null  float64
 33  payment_value                  113193 non-null  float64
 34  review_id                      113193 non-null  str
 35  review_score                   113193 non-null  float64
 36  review_comment_title           113193 non-null  str
 37  review_comment_message         113193 non-null  str
 38  review_creation_date           113193 non-null  datetime64[us]
 39  review_answer_timestamp        113193 non-null  datetime64[us]
dtypes: datetime64[us](8), float64(15), int64(1), str(16)
memory usage: 35.4 MB

In [43]:
import numpy as np
import pandas as pd

# 1. Filter for negative reviews using master_df
negative_reviews = master_df[master_df['review_score'] <= 2].copy()

# 2. Function to categorize complaints based on Portuguese text keywords
def categorize_complaint(text):
    if pd.isna(text):
        return 'No Comment'
    text = str(text).lower()
    if any(k in text for k in ['demor', 'atras', 'nao chegou', 'prazo']):
        return 'Late / Delayed'
    elif any(k in text for k in ['quebrad', 'estragad', 'defeito', 'danificad']):
        return 'Damaged / Defective'
    elif any(k in text for k in ['errado', 'diferente', 'faltou', 'veio']):
        return 'Wrong / Incomplete'
    elif any(k in text for k in ['nao recebi', 'nunca']):
        return 'Not Delivered'
    else:
        return 'Other Complaint'

# Combine title and message for keyword matching
comment_text = (
    negative_reviews['review_comment_title'].fillna('') + " " + 
    negative_reviews['review_comment_message'].fillna('')
)

# 3. Apply categorization
negative_reviews['Complaint_Category'] = comment_text.apply(categorize_complaint)

# 4. Deduplicate by review_id before counting (prevents multi-item order inflation)
complaint_counts = (
    negative_reviews.drop_duplicates(subset=['review_id'])['Complaint_Category']
    .value_counts()
    .reset_index(name='Negative Review Count')
)

print(complaint_counts)

    Complaint_Category  Negative Review Count
0      Other Complaint                   8565
1   Wrong / Incomplete                   1457
2       Late / Delayed                   1280
3  Damaged / Defective                    452
4        Not Delivered                    254